home:
    path: /
    controller: App\Controller\MainController:home

logout:
    path: /logout

login:
    path: /login
    controller: App\Controller\SecurityController:login

front:
  resource: "routes/front.yml"

admin:
  resource: "routes/admin.yml"
  prefix: /admin
