App\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 100
        email:
            type: string
        password:
            type: string
            length: 100
        roles:
            type: array
